# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('login_attempts', models.PositiveIntegerField()),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempt_time'],
            },
        ),
    ]
