# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0002_auto_20170131_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessattempt',
            name='user_ip',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessattempt',
            name='attempt_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 13, 5, 15, 260000, tzinfo=utc)),
        ),
    ]
