# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0003_auto_20170131_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessattempt',
            name='attempt_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 13, 5, 42, 600000, tzinfo=utc)),
        ),
    ]
