# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20161114_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='favorites',
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
