# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20161116_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
