# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20161116_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
