# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20170128_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
